### PR TITLE
Make Icon Look Better

### PR DESCRIPTION
**Pull request by juniorRubyist**
I think that the red and green for the icon is an eyesore, so I propose that the icon change transparency instead of change color to symbolize the status.

100% White (`#ffff`) would be On
47% White (`#fff7`) would be Off
and 27% White (`#ff4`) with a `?` would be Unknown

### CODE REVIEW

**Comment by juniorRubyist** [comment]
It can be installed using the manual link option in the OctoPrint Plugin Manager:
`https://github.com/juniorRubyist/OctoPrint-Tasmota/archive/patch-1.zip`

**Comment by juniorRubyist** [comment]
I’d like to have your input on it.

**Comment by juniorRubyist** [comment]
I’m interested in your input on my modification of this plugin.

**Comment by jneilliii** [comment]
I thought I had already replied. The issue with your changes is that they only really work if your using one of the color themes. If you're using default the icon is more difficult to see.

**Comment by juniorRubyist** [comment]
I implemented your request.

**Comment by juniorRubyist** [comment]
@jneilliii I fixed your suggestions.

**Comment by jneilliii** [comment]
Sorry for the delay.  I was wanting to take a different approach for this request and just now got the time to work on it.  I have made the colors configurable in the plug's individual settings.  I need to verify it doesn't break with multiple plugs, but it seems to be working fine so far with a single plug.  Give it a try and let me know if that helps in your situation/opinion relative to the look of the icon. Install using the url below in plugin manager.

https://github.com/jneilliii/OctoPrint-Tasmota/archive/0.8.6.zip

**Pull request closed without merging**
