### PR TITLE
Added label on navbar to work with touch UI

### PR DESCRIPTION
**Pull request by valerie16901**

### CODE REVIEW

**Comment by jneilliii** [comment]
Do you have any photos showing the difference?

**Comment by jneilliii** [comment]
Don't think this works as anticipated.

image

Also messes up in the default ui.

image

**Comment by jneilliii** [comment]
I think I have a working solution.  Install from this url and let me know if it's what you were expecting.

https://github.com/jneilliii/OctoPrint-Tasmota/archive/TouchUI-Labeling.zip

**Comment by jneilliii** [comment]
I've implemented this a different way in the latest version 0.8.5 that maintains the default ui as just icons and label is only displayed while TouchUI is enabled.

**Comment by valerie16901** [comment]
Oh! sorry for the late reply, I been busy, thank you very much for the fix, I really appreciate it!

**Pull request closed without merging**
